// Generated by gencpp from file janken_pkg/AddTwoInts.msg
// DO NOT EDIT!


#ifndef JANKEN_PKG_MESSAGE_ADDTWOINTS_H
#define JANKEN_PKG_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <janken_pkg/AddTwoIntsRequest.h>
#include <janken_pkg/AddTwoIntsResponse.h>


namespace janken_pkg
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace janken_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::janken_pkg::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::janken_pkg::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::janken_pkg::AddTwoInts > {
  static const char* value()
  {
    return "janken_pkg/AddTwoInts";
  }

  static const char* value(const ::janken_pkg::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::janken_pkg::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::janken_pkg::AddTwoInts > 
template<>
struct MD5Sum< ::janken_pkg::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::janken_pkg::AddTwoInts >::value();
  }
  static const char* value(const ::janken_pkg::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::janken_pkg::AddTwoIntsRequest> should match 
// service_traits::DataType< ::janken_pkg::AddTwoInts > 
template<>
struct DataType< ::janken_pkg::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::janken_pkg::AddTwoInts >::value();
  }
  static const char* value(const ::janken_pkg::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::janken_pkg::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::janken_pkg::AddTwoInts > 
template<>
struct MD5Sum< ::janken_pkg::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::janken_pkg::AddTwoInts >::value();
  }
  static const char* value(const ::janken_pkg::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::janken_pkg::AddTwoIntsResponse> should match 
// service_traits::DataType< ::janken_pkg::AddTwoInts > 
template<>
struct DataType< ::janken_pkg::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::janken_pkg::AddTwoInts >::value();
  }
  static const char* value(const ::janken_pkg::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JANKEN_PKG_MESSAGE_ADDTWOINTS_H
